version: "3.8"

services:
  app:
    image: pharmacy-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pharmacy-app
    ports:
      - "80:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: always
